### ISSUE TITLE
Internal Error: get_unit(): Bad internal unit KIND

### ISSUE THREAD

**Issue by Igor-SV** [ralna/GALAHAD#2]
Dear GALAHAD users,

After having upgraded to gfortran 7.3.0, I cannot use LANCELOT any more due to the error:
At line 630 of file lancelot_simple.f90
Internal Error: get_unit(): Bad internal unit KIND

Could you please help me out with this issue?

Best regards,
Igor

**Comment by nimgould** [comment]
Dear Igor

I have just tried a fresh install with gfortran-7 and all seems ok.

(gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)

I wonder if you have elements of an old installation hanging around?

I suggest you cd $GALAHAD/src and try

make -s -f $GALAHAD/makefiles/pc64.lnx.gfo cleanall
make -s -f $GALAHAD/makefiles/pc64.lnx.gfo

to see if this helps. Otherwise, maybe you have added a compiler
flag that has raised a fortran issue? I'd need to see the result of

cd $GALAHAD/src/lancelot_simple ; make -f $GALAHAD/makefiles/pc64.lnx.gfo

in this case. But try the cleanall above first.

Best wishes

Nick

-- 
Nicholas I. M. Gould
Scientific Computing Department            email: nick.gould@stfc.ac.uk
G39, R71 Rutherford Appleton Laboratory    phone: 0(44)1235 445801
Chilton, Oxon OX11 0QX England EU
www: http://www.numerical.rl.ac.uk/people/nimg

**Comment by Igor-SV** [comment]
Dear Nick,

Thank you so much!
The normal functionality restored!

Best regards,
Igor
